# Generated by Django 5.2.14 on 2026-05-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0003_newsletter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsletter",
            name="email",
            field=models.EmailField(max_length=255),
        ),
    ]
