# Generated by Django 5.2.14 on 2026-05-17 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_category_post_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.ManyToManyField(related_name="posts", to="blog.category"),
        ),
    ]
