# Generated by Django 5.2.14 on 2026-06-09 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_comment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["-created_date"]},
        ),
        migrations.AddField(
            model_name="post",
            name="login_require",
            field=models.BooleanField(default=False),
        ),
    ]
